//Funciones de Semestres
export const FETCH_DETALLE_SEMESTRE = "FETCH_DETALLE_SEMESTRE";
export const FETCH_SEMESTRES = "FETCH_SEMESTRES";
export const CLEAN_DETALLE_SEMESTRE = "CLEAN_DETALLE_SEMESTRE";
export const CLEAN_SEMESTRES = "CLEAN_SEMESTRES";
