//Funciones de Objetivos Educacionales
export const FETCH_OBJETIVOS_EDUCACIONALES = "FETCH_OBJETIVOS_EDUCACIONALES";
export const FETCH_OBJETIVO_EDUCACIONAL = "FETCH_OBJETIVO_EDUCACIONAL";
export const CLEAN_OBJETIVO_EDUCACIONAL = "CLEAN_OBJETIVO_EDUCACIONAL";
export const BUSCAR_OBJETIVOS_EDUCACIONALES = "BUSCAR_OBJETIVOS_EDUCACIONALES";
