//Funciones de REs
export const FETCH_PROGRAMAS_MEDICION = "FETCH_PROGRAMAS_MEDICION";
export const FETCH_PROGRAMA_MEDICION = "FETCH_PROGRAMA_MEDICION";
export const FETCH_NO_RESULTADO_ESTUDIANTE_MEDICION =
    "FETCH_NO_RESULTADO_ESTUDIANTE_MEDICION";
