//Funciones de Facultades
export const FETCH_ASISTENTES = "FETCH_ASISTENTES";
export const BUSCAR_ASISTENTES = "BUSCAR_ASISTENTES";
export const FETCH_NOASISTENTES = "FETCH_NOASISTENTES";
export const FETCH_ADDASISTENTES = "FETCH_ADDASISTENTES";
export const FETCH_DELETEASISTENTES = "FETCH_DELETEASISTENTES";
