export const FETCH_USUARIOS = "FETCH_USUARIOS";
export const FETCH_USUARIO = "FETCH_USUARIO";
export const BUSCAR_USUARIOS = "BUSCAR_USUARIOS";
export const ERRORES_CARGA_MASIVA = "ERRORES_CARGA_MASIVA";
